services:

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"

    environment:
      ORACLE_PASSWORD: 123456
      APP_USER: appuser
      APP_USER_PASSWORD: 123456

    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./db/init:/container-entrypoint-initdb.d

    restart: unless-stopped

volumes:
  oracle-data:
